name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: |
          docker build . --file Dockerfile --tag ghcr.io/abos-gergo/event-manager:$TAG --tag ghcr.io/abos-gergo/event-manager:latest
          docker login ghcr.io -u abos-gergo -p ${{secrets.GHCR_TOKEN}}
          docker push ghcr.io/abos-gergo/event-manager:$TAG
          docker push ghcr.io/abos-gergo/event-manager:latest
